services:
  - name: map-geo-geowebcache-lab
    host: maptest.lb.v1
    #host: map-test.264e6f-dev.svc
    # port: 80
    # protocol: http
    tags: [ns.map-geo-design]
    retries: 0
    routes:
      - name: map-geo-geowebcache-lab
        tags: [ns.map-geo-design]
        hosts:
          - map-geo-lab.api.gov.bc.ca
        paths:
          - /
        methods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        strip_path: false
        https_redirect_status_code: 426
        path_handling: v0
        request_buffering: true
        response_buffering: true
