gwc:
  enabled: true

  replicaCount: 1

  rollingUpdate:
    maxUnavailable: 100%
    maxSurge: 0%

  resources:
    limits:
      cpu: 800m
      memory: 1024Mi
    requests:
      cpu: 100m
      memory: 512Mi

  image:
    repository: ghcr.io/bcgov/map-geo-service/map-geowebcache
    #repository: artifacts.developer.gov.bc.ca/a264-docker/map-geowebcache
    pullPolicy: Always
    tag: dev

  imagePullSecrets:
    - name: dev-github-read-packages-creds

  containerPort: 8080

  service:
    port: 80

  env:
    JAVA_OPTS:
      value: "-Xms512m -Xmx1024m"
    WMS_BASE_URL:
      value: "https://map-geoserver-imai.api.gov.bc.ca/geo/pub/ows"

  config: []

  persistence:
    catalina:
      mountPath: /usr/local/tomcat/conf/Catalina/localhost
    cache:
      mountPath: /geowebcache/cache
      # claimName: externally-created-pvc-claim
      # size: 1Gi
      # storageClassName: netapp-block-standard
      # storageAccessMode: ReadWriteOnce

    logs:
      mountPath: /usr/local/tomcat/logs

  nameOverride: map-geowebcache

  extraLabels:
    role: geowebcache
