gwc:
  enabled: true

  useStatefulSet: true

  replicaCount: 5

  rollingUpdate:
    maxUnavailable: 100%
    maxSurge: 0%

  readinessProbe:
    httpGet:
      path: /gwc
      port: http
    initialDelaySeconds: 15
    periodSeconds: 15
    timeoutSeconds: 5

  resources:
    limits:
      cpu: 800m
      memory: 3Gi
    requests:
      cpu: 100m
      memory: 512Mi

  image:
    repository: ghcr.io/bcgov/map-geo-service/map-geowebcache
    #repository: artifacts.developer.gov.bc.ca/a264-docker/map-geowebcache
    pullPolicy: Always
    tag: dev

  imagePullSecrets:
    - name: dev-github-read-packages-creds

  containerPort: 8080

  service:
    port: 80

  env:
    JAVA_OPTS:
      value: "-Xms1024m -Xmx2048m"
    WMS_BASE_URL:
      # value: "https://map-geoserver-imai.api.gov.bc.ca/geo/pub/ows"
      value: "https://map-geoserver.dev.api.gov.bc.ca/geoserver/wms"
    S3_ENDPOINT:
      value: "TO_BE_SET"
      secure: true
    S3_CACHE_BUCKET:
      value: "TO_BE_SET"
      secure: true
    S3_ACCESS_KEY:
      value: "TO_BE_SET"
      secure: true
    S3_SECRET_KEY:
      value: "TO_BE_SET"
      secure: true

  config: []

  persistence:
    catalina:
      mountPath: /usr/local/tomcat/conf/Catalina/localhost
    cache:
      mountPath: /geowebcache/cache
      #claimName: map-geowebcache-shared-cache
      # claimName: externally-created-pvc-claim
      # size: 1Gi
      # storageClassName: netapp-block-standard
      # storageAccessMode: ReadWriteOnce

    logs:
      mountPath: /usr/local/tomcat/logs

  nameOverride: map-geowebcache

  extraLabels:
    role: geowebcache
    solution: dss-maps
