gwc:
  enabled: true

  useStatefulSet: true

  replicaCount: 1

  autoscaling:
    enabled: false

  # NOT RELEVANT WHEN useStatefulSet=true
  # rollingUpdate:
  #   maxUnavailable: 0%
  #   maxSurge: 100%

  livenessProbe:
    httpGet:
      path: /gwc
      port: http
    initialDelaySeconds: 60
    periodSeconds: 15
    timeoutSeconds: 5
    failureThreshold: 3

  readinessProbe:
    httpGet:
      path: /gwc
      port: http
    initialDelaySeconds: 15
    periodSeconds: 15
    timeoutSeconds: 5

  resources:
    limits:
      cpu: 800m
      memory: 3Gi
    requests:
      cpu: 100m
      memory: 512Mi

  image:
    repository: ghcr.io/bcgov/map-geo-service/map-geowebcache
    #repository: artifacts.developer.gov.bc.ca/a264-docker/map-geowebcache
    pullPolicy: Always
    tag: dev

  imagePullSecrets:
    - name: dev-github-read-packages-creds

  containerPort: 8080

  service:
    port: 80

  env:
    TZ:
      value: "America/Vancouver"
    JAVA_OPTS:
      value: "-Xms1024m -Xmx2048m"
    WMS_BASE_URL:
      value: "https://map-geoserver.dev.api.gov.bc.ca/geoserver/wms"

  config: []

  persistence:
    catalina:
      mountPath: /usr/local/tomcat/conf/Catalina/localhost
    cache:
      mountPath: /geowebcache/cache
    logs:
      mountPath: /usr/local/tomcat/logs

  nameOverride: map-geowebcache

  extraLabels:
    role: geowebcache
    solution: dss-maps
