gwc:
  replicaCount: 15

  useStatefulSet: false

  rollingUpdate:
    maxUnavailable: 10%
    maxSurge: 10%

  autoscaling:
    enabled: false
    minReplicas: 5
    maxReplicas: 15
    targetCPUUtilizationPercentage: 60

  imagePullSecrets:
    - name: prod-github-read-packages-creds

  env:
    WMS_BASE_URL:
      value: "https://map-geoserver-imai.api.gov.bc.ca/geo/pub/ows"
      # value: "https://map-geoserver.api.gov.bc.ca/geoserver/wms"
