gwc:
  replicaCount: 1

  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 60

  imagePullSecrets:
    - name: test-github-read-packages-creds

  env:
    WMS_BASE_URL:
      value: "https://map-geoserver.test.api.gov.bc.ca/geoserver/wms"
