gwc:
  replicaCount: 20

  rollingUpdate:
    maxUnavailable: 0
    maxSurge: 1

  autoscaling:
    enabled: false
    minReplicas: 5
    maxReplicas: 20
    targetCPUUtilizationPercentage: 60

  imagePullSecrets:
    - name: prod-github-read-packages-creds
