gwc:
  enabled: true

  replicaCount: 1

  rollingUpdate:
    maxUnavailable: 100%
    maxSurge: 0%

  resources:
    limits:
      cpu: 200m
      memory: 1024Mi
    requests:
      cpu: 50m
      memory: 100Mi

  image:
    repository: artifacts.developer.gov.bc.ca/a264-docker/map-geowebcache
    pullPolicy: Always
    tag: dev

  imagePullSecrets:
    - name: artifactory-pull

  containerPort: 8080

  service:
    port: 80

  env:
    JAVA_OPTS:
      value: "-Xms512m -Xmx1024m"
    WMS_BASE_URL:
      value: "https://openmaps.gov.bc.ca"

  config: []

  persistence:
    catalina:
      mountPath: /usr/local/tomcat/conf/Catalina/localhost
    logs:
      mountPath: /usr/local/tomcat/logs

  nameOverride: map-geowebcache

  extraLabels:
    role: geowebcache
