gwc:
  replicaCount: 12

  # NOT RELEVANT WHEN useStatefulSet=true
  # rollingUpdate:
  #   maxUnavailable: 0
  #   maxSurge: 1

  autoscaling:
    enabled: false
    minReplicas: 5
    maxReplicas: 20
    targetCPUUtilizationPercentage: 60

  env:
    WMS_BASE_URL:
      value: "https://map-geoserver-imai.api.gov.bc.ca/geo/pub/ows"
      # value: "https://map-geoserver.api.gov.bc.ca/geoserver/wms"

  imagePullSecrets:
    - name: prod-github-read-packages-creds
