apiVersion: v2
name: prom-metrics-vms
description: A Helm chart for deploying a proxied scraper

type: application

version: 0.2.8

appVersion: 1.0.0

dependencies:
  - name: generic-api
    version: 0.2.8
    repository: https://bcgov.github.io/helm-charts
    condition: prom.enabled
    alias: prom
