geoserver:
  enabled: true

  replicaCount: 1

  rollingUpdate:
    maxUnavailable: 0%
    maxSurge: 100%

  readinessProbe:
    httpGet:
      path: /geoserver
      port: http
    initialDelaySeconds: 15
    periodSeconds: 15
    timeoutSeconds: 5

  resources:
    limits:
      cpu: 800m
      memory: 1Gi
    requests:
      cpu: 50m
      memory: 100Mi

  image:
    repository: ghcr.io/bcgov/map-geo-service/map-geoserver
    #repository: artifacts.developer.gov.bc.ca/a264-docker/map-geoserver
    pullPolicy: Always
    tag: dev

  imagePullSecrets:
    - name: dev-github-read-packages-creds
    # - name: artifactory-pull

  containerPort: 8080

  service:
    port: 80

  env:
    TZ:
      value: "America/Vancouver"
    HTTP_PROXY_NAME:
      value: map-geoserver-lab-api-gov-bc-ca.dev.api.gov.bc.ca
    HTTP_SCHEME:
      value: https
    PROXY_BASE_URL:
      value: https://map-geoserver-lab-api-gov-bc-ca.dev.api.gov.bc.ca/geoserver
    S3_ENDPOINT:
      value: TO_BET_SET
      secure: true
    S3_BUCKET:
      value: TO_BET_SET
      secure: true
    S3_ACCESS_KEY:
      value: TO_BET_SET
      secure: true
    S3_SECRET_KEY:
      value: TO_BET_SET
      secure: true

  config: []

  persistence:
    catalina:
      mountPath: /usr/local/tomcat/conf/Catalina/localhost
    geoserver-data:
      mountPath: /opt/geoserver_data
    dotmc:
      mountPath: /.mc

  nameOverride: map-geoserver

  extraLabels:
    role: geoserver
    solution: dss-maps

  extraContainers:
    s3-sync:
      image:
        repository: docker.io/minio/mc
        pullPolicy: IfNotPresent
        tag: RELEASE.2023-05-04T18-10-16Z

      resources:
        limits:
          cpu: 50m
          memory: 100Mi
        requests:
          cpu: 25m
          memory: 50Mi

      volumeMounts:
        - name: dotmc-vol
          mountPath: /.mc
        - name: geoserver-data-vol
          mountPath: /opt/geoserver_data

      command:
        - bash
        - -e
        - -c
        - |
          mc alias set s3 $S3_ENDPOINT $S3_ACCESS_KEY $S3_SECRET_KEY

          while true
          do
            echo `date` `mc mirror --preserve --overwrite --no-color --json s3/$S3_BUCKET/datadrop /opt/geoserver_data/data/geopackage/`
            sleep 15
          done
