geoserver:
  replicaCount: 5

  rollingUpdate:
    maxUnavailable: 0%
    maxSurge: 50%

  env:
    HTTP_PROXY_NAME:
      value: map-geoserver.api.gov.bc.ca
    HTTP_SCHEME:
      value: https
    PROXY_BASE_URL:
      value: https://map-geoserver.api.gov.bc.ca/geoserver

  image:
    pullPolicy: IfNotPresent
    tag: TO_BE_SET

  imagePullSecrets:
    - name: prod-github-read-packages-creds
