geoserver:
  env:
    HTTP_PROXY_NAME:
      value: map-geoserver-api-gov-bc-ca.test.api.gov.bc.ca
    HTTP_SCHEME:
      value: https
    PROXY_BASE_URL:
      value: https://map-geoserver-api-gov-bc-ca.test.api.gov.bc.ca/geoserver

  image:
    pullPolicy: IfNotPresent
    tag: TO_BE_SET

  imagePullSecrets:
    - name: test-github-read-packages-creds
