services:
  - name: map-geo-geowebcache-dev
    host: map-geowebcache-dev.264e6f-dev.svc
    tags: [ns.dss-map-geo]
    port: 80
    protocol: http
    retries: 0
    routes:
      - name: map-geo-geowebcache-dev
        tags: [ns.dss-map-geo]
        hosts:
          - map-gwc.dev.api.gov.bc.ca
        paths:
          - /
        methods:
          - GET
          - POST
        strip_path: false
        https_redirect_status_code: 426
        path_handling: v0
        request_buffering: true
        response_buffering: true

  - name: map-geoserver-imai-dev
    host: openmaps.gov.bc.ca
    tags: [ns.dss-map-geo]
    port: 443
    protocol: https
    retries: 0
    routes:
      - name: map-geoserver-imai-dev
        tags: [ns.dss-map-geo]
        hosts:
          - map-geoserver-imai.api.gov.bc.ca
        paths:
          - /
        methods:
          - GET
        strip_path: false
        https_redirect_status_code: 426
        path_handling: v0
        request_buffering: true
        response_buffering: true

  - name: map-geo-geowebcache-prod
    host: map-geowebcache-prod.264e6f-prod.svc
    tags: [ns.dss-map-geo]
    port: 80
    protocol: http
    retries: 0
    connect_timeout: 5000
    read_timeout: 5000
    write_timeout: 5000
    plugins:
      - name: response-transformer
        tags: [ns.dss-map-geo]
        config:
          add:
            headers:
              - "X-Geo-Cache-Source: ocp"
    routes:
      - name: map-geo-geowebcache-prod
        tags: [ns.dss-map-geo]
        hosts:
          - map-gwc.api.gov.bc.ca
        paths:
          - /
        methods:
          - GET
          - POST
        strip_path: false
        https_redirect_status_code: 426
        path_handling: v0
        request_buffering: true
        response_buffering: true
