name: Release Image

on:
  push:
    branches: [dev, image/*]

env:
  REGISTRY: artifacts.developer.gov.bc.ca

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ secrets.ARTIFACTORY_REPO_NAME }}/map-geowebcache

      - name: Set DEPLOY_ID which will deploy a custom deploy to 'dev' environment
        run: |
          echo "DEPLOY_ID=${{ steps.docker_meta.outputs.version }}" >> $GITHUB_OUTPUT
          echo "APP_VERSION=${{ fromJSON(steps.docker_meta.outputs.json).labels['org.opencontainers.image.version'] }}" >> $GITHUB_OUTPUT
          echo "APP_REVISION=${{ fromJSON(steps.docker_meta.outputs.json).labels['org.opencontainers.image.revision'] }}" >> $GITHUB_OUTPUT
        id: set-deploy-id

      - uses: actions/checkout@v2

      - name: Login to Artifactory
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v2

      # - name: Set up Docker Buildx
      #   id: buildx
      #   uses: docker/setup-buildx-action@v2

      - name: Build
        uses: docker/build-push-action@v3
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: .
          file: geowebcache/Dockerfile
          tags: ${{ env.REGISTRY }}/${{ secrets.ARTIFACTORY_REPO_NAME }}/map-geowebcache:${{ steps.release.outputs.tag_name }}
          push: true
          build-args: |
            GITHUB_API_TOKEN=${{ secrets.REGISTRY_PASSWORD }}
            APP_VERSION=${{ steps.set-deploy-id.outputs.APP_VERSION }}
            APP_REVISION=${{ steps.set-deploy-id.outputs.APP_REVISION }}
